# -----------------------------------------------------
# AUTHOR: 27Aaron
# UPDATED: 2026-08-07 23:53:24
# REPO: https://github.com/27Aaron/ProxyRules
# LINK: https://github.com/27Aaron/ProxyRules/raw/refs/heads/main/Surge/Config/Surge-Lite.conf
# -----------------------------------------------------

[General]
# > Log level
loglevel = notify
show-error-page-for-reject = true

# > Test URL
internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://cp.cloudflare.com/generate_204
test-timeout = 3

# > GeoIP
geoip-maxmind-url = https://github.com/Loyalsoldier/geoip/raw/release/Country-without-asn.mmdb

# > IPv6
ipv6 = true
ipv6-vif = auto

# > DNS
dns-server = system, 119.29.29.29, 223.5.5.5
encrypted-dns-server = https://doh.pub/dns-query
hijack-dns = 8.8.8.8:53, 1.1.1.1:53, 8.8.4.4:53
encrypted-dns-follow-outbound-mode = true

# > skip-proxy
skip-proxy = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, ::1/128, fc00::/7, fe80::/10, ff00::/8, ::ffff:0:0:0:0/96, localhost, *.local, captive.apple.com, e.crashlytics.com

# > Other
udp-priority = true
compatibility-mode = 0
exclude-simple-hostnames = true
udp-policy-not-supported-behaviour = reject

[Proxy Group]
# > Main
Proxies = select, Manual, HKG, JPN, USA
Manual = select, include-all-proxies=true, interval=600, tolerance=20, evaluate-before-use=true
Google = select, Proxies, Manual, HKG, JPN, USA
Twitter = select, Proxies, Manual, HKG, JPN, USA
Final = select, Proxies, DIRECT, Manual

# > Regions
HKG = url-test, include-other-group=Manual, interval=300, tolerance=20, policy-regex-filter=(?i)🇭🇰|香港|Hong.?Kong|\bHKG\b|\bHK\b, evaluate-before-use=true
JPN = url-test, include-other-group=Manual, interval=300, tolerance=20, policy-regex-filter=(?i)🇯🇵|日本|Japan|\bJPN\b|\bJP\b, evaluate-before-use=true
USA = url-test, include-other-group=Manual, interval=300, tolerance=20, policy-regex-filter=(?i)🇺🇸|美国|美國|United.?States|America|\bUSA\b|\bUS\b, evaluate-before-use=true

[Rule]
# > Reject
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/category-ads-all@ads/category-ads-all@ads.list,REJECT

# > Private
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/private/private.list,DIRECT

# > Google
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/google/google.list,Google

# > Twitter
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/twitter/twitter.list,Twitter

# > Proxy
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/geolocation-!cn/geolocation-!cn.list,Proxies

# > Direct CN
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/cn/cn.list,DIRECT

# > Final
FINAL,Final,dns-failed

[Host]
