# -----------------------------------------------------
# AUTHOR: 27Aaron
# UPDATED: 2026-08-07 23:53:24
# REPO: https://github.com/27Aaron/ProxyRules
# LINK: https://github.com/27Aaron/ProxyRules/raw/refs/heads/main/Shadowrocket/Config/Shadowrocket-Lite.conf
# -----------------------------------------------------

[General]
# > IPv6 / System
ipv6 = true
bypass-system = true

# > skip-proxy / TUN exclude
skip-proxy = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, localhost, *.local, captive.apple.com, e.crashlytics.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32

# > DNS
dns-server = system, 223.5.5.5, 119.29.29.29
fallback-dns-server = 8.8.8.8, 1.1.1.1
doh-server = https://doh.pub/dns-query
private-ip-answer = true
always-reject-url-rewrite = false
hijack-dns = 8.8.8.8:53, 1.1.1.1:53

# > Other
udp-policy-not-supported-behaviour = reject
test-timeout = 3
internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://cp.cloudflare.com/generate_204

[Proxy Group]
# > Main
Proxies = select, Manual, HKG, JPN, USA, url=http://cp.cloudflare.com/generate_204, interval=600
Manual = select, include-all-proxies=true, url=http://cp.cloudflare.com/generate_204, interval=600
Google = select, Proxies, Manual, HKG, JPN, USA, url=http://cp.cloudflare.com/generate_204, interval=600
Twitter = select, Proxies, Manual, HKG, JPN, USA, url=http://cp.cloudflare.com/generate_204, interval=600
Final = select, Proxies, DIRECT, Manual, url=http://cp.cloudflare.com/generate_204, interval=600

# > Regions
HKG = url-test, include-other-group=Manual, url=http://cp.cloudflare.com/generate_204, interval=300, tolerance=20, policy-regex-filter=(?i)(🇭🇰|香港|Hong.?Kong|\bHKG\b|\bHK\b)
JPN = url-test, include-other-group=Manual, url=http://cp.cloudflare.com/generate_204, interval=300, tolerance=20, policy-regex-filter=(?i)(🇯🇵|日本|Japan|\bJPN\b|\bJP\b)
USA = url-test, include-other-group=Manual, url=http://cp.cloudflare.com/generate_204, interval=300, tolerance=20, policy-regex-filter=(?i)(🇺🇸|美国|美國|United.?States|America|\bUSA\b|\bUS\b)

[Rule]
# > Reject
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/category-ads-all@ads/category-ads-all@ads.list,REJECT

# > Private
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/private/private.list,DIRECT

# > Google
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/google/google.list,Google

# > Twitter
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/twitter/twitter.list,Twitter

# > Proxy
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/geolocation-!cn/geolocation-!cn.list,Proxies

# > Direct CN
RULE-SET,https://fastly.jsdelivr.net/gh/27Aaron/ProxyRules@rules/ruleset/cn/cn.list,DIRECT

# > Final
FINAL,Final

[Host]

[URL Rewrite]

[MITM]
enable = false
hostname =
